const TeamFortress2 = require('./index.js');

TeamFortress2.GCGoodbyeReason = {
	GC_GOING_DOWN: 1,
	NO_SESSION: 2
};

TeamFortress2.TradeResponse = {
	Accepted: 0,
	Declined: 1,
	TradeBannedInitiator: 2,
	TradeBannedTarget: 3,
	TargetAlreadyTrading: 4,
	Disabled: 5,
	NotLoggedIn: 6,
	Cancel: 7,
	TooSoon: 8,
	TooSoonPenalty: 9,
	ConnectionFailed: 10,
	AlreadyTrading: 11,
	AlreadyHasTradeRequest: 12,
	NoResponse: 13,
	CyberCafeInitiator: 14,
	CyberCafeTarget: 15,
	SchoolLabInitiator: 16,
	SchoolLabTarget: 16,
	InitiatorBlockedTarget: 18,
	InitiatorNeedsVerifiedEmail: 20,
	InitiatorNeedsSteamGuard: 21,
	TargetAccountCannotTrade: 22,
	InitiatorSteamGuardDuration: 23,
	InitiatorPasswordResetProbation: 24,
	InitiatorNewDeviceCooldown: 25,
	OKToDeliver: 50
};

TeamFortress2.Class = {
	Scout: 1,
	Sniper: 2,
	Soldier: 3,
	Demoman: 4,
	Medic: 5,
	Heavy: 6,
	Pyro: 7,
	Spy: 8,
	Engineer: 9
};

TeamFortress2.ItemSlot = {
	Primary: 0,
	Secondary: 1,
	Melee: 2,
	// 3 appears to be unused
	Sapper: 4, // Sapper
	PDA: 5,
	PDA2: 6,
	Cosmetic1: 7,
	Cosmetic2: 8,
	Action: 9,
	Cosmetic3: 10,
	Taunt1: 11,
	Taunt2: 12,
	Taunt3: 13,
	Taunt4: 14,
	Taunt5: 15,
	Taunt6: 16,
	Taunt7: 17,
	Taunt8: 18
};

TeamFortress2.ItemFlags = {
	CannotTrade: (1 << 0),
	CannotCraft: (1 << 1),
	NotEcon: (1 << 3),
	Preview: (1 << 7)
};

TeamFortress2.War = {
	HeavyVsPyro: 0
};

TeamFortress2.HeavyVsPyroWarSide = {
	Heavy: 0,
	Pyro: 1
};

TeamFortress2.CraftRecipes = {
  SmeltClassWeapons: 3,
  CombineScrapMetal: 4,
  CombineReclaimedMetal: 5,
  FabricateHeadgear: 6,
  FabricateClassToken: 7,
  FabricateSlotToken: 8,
  RebuildHeadgear: 9,
  FabricateClassHeadgear: 10,
  FabricateClassWeapon: 11,
  RebuildClassToken: 13,
  RebuildSlotToken: 14,
  SmeltTokens: 15,
  FabricateBonkHelm: 16,
  FabricateCritaCola: 17,
  FabricateThePainTrain: 18,
  FabricateTheGunboats: 19,
  FabricateTheDalokohsBar: 20,
  FabricateTheHomewrecker: 21,
  SmeltReclaimedMetal: 22,
  SmeltRefinedMetal: 23,
  FabricateTheScotsmansSkullcutter: 24,
  FabricateTheTribalmansShiv: 25,
  FabricateTheSouthernHospitality: 26,
  FabricateThePowerjack: 27,
  FabricateTheDegreaser: 28,
  FabricateTheShortstop: 29,
  FabricateTheHolyMackerel: 30,
  FabricateMadMilk: 31,
  FabricateLEtranger: 32,
  FabricateYourEternalReward: 33,
  FabricateTheBattalionsBackup: 34,
  FabricateTheBlackBox: 35,
  FabricateTheSydneySleeper: 36,
  FabricateDarwinsDangerShield: 37,
  FabricateTheBushwacka: 38,
  FabricateGlovesofRunningUrgently: 39,
  FabricateTheVitaSaw: 40,
  FabricateSetHeadgear: 41,
  HalloweenMaskSaxtonHale: 42,
  TheHorselessHeadlessHorsemansHeadtaker: 43,
  HauntedHat: 44,
  FabricateTheAmputator: 45,
  FabricateTheCrusadersCrossbow: 46,
  FabricateTheUllapoolCaber: 47,
  FabricateTheLochnLoad: 48,
  FabricateWarriorsSpirit: 49,
  FabricateTheBuffaloSteakSandvich: 50,
  FabricateTheBrassBeast: 51,
  FabricateTheCandyCane: 52,
  FabricateTheClaidheamohmor: 53,
  FabricateTheBackScratcher: 54,
  FabricateTheBostonBasher: 55,
  FabricateFistsofSteel: 56,
  FabricateTheJag: 57,
  FabricateTheAxtinguisher: 58,
  FabricateSunonaStick: 59,
  FabricateTheHalfZatoichi: 60,
  FabricateTheConcheror: 61,
  FabricateConniversKunai: 62,
  FabricateTheFanOWar: 63,
  Fishcake: 64,
  SpaceChemPin: 65,
  FabricateTheSodaPopper: 66,
  FabricateTheWinger: 67,
  FabricateTheAtomizer: 68,
  FabricateTheFamilyBusiness: 69,
  FabricateTomislav: 70,
  FabricateTheEvictionNotice: 71,
  FabricateTheEnforcer: 72,
  FabricateTheBigEarner: 73,
  FabricateTheBazaarBargain: 74,
  FabricateTheShahanshah: 75,
  FabricateThePersianPersuader: 76,
  FabricateTheSplendidScreen: 77,
  FabricateAliBabasWeeBooties: 78,
  FabricateTheLibertyLauncher: 79,
  FabricateTheReserveShooter: 80,
  FabricateTheMarketGardener: 81,
  FabricateTheMantreads: 82,
  FabricateTheDisciplinaryAction: 83,
  FabricateTheDetonator: 84,
  FabricateTheOverdose: 85,
  FabricateTheSolemnVow: 86,
  FabricateTheQuickFix: 87,
  FabricateTheCowMangler5000: 88,
  FabricateTheRighteousBison: 89,
  FabricateTheDiamondback: 90,
  FabricateTheMachina: 91,
  FabricateTheWidowmaker: 92,
  FabricateTheShortCircuit: 93,
  FabricateTheOriginal: 94,
  FabricateTheSpyCicle: 95,
  FabricateTheHolidayPunch: 96,
  FabricateTheWrapAssassin: 97,
  FabricateThePhlogistinator: 98,
  FabricateTheManmelter: 99,
  FabricateTheThirdDegree: 100,
  FabricateThePomson6000: 101,
  FabricateTheEurekaEffect: 102,
  FabricateTheCozyCamper: 103,
  FabricateTheEscapePlan: 104,
  PileOfAsh: 105,
  FabricateTheBeggarsBazooka: 106,
  FabricateTheHitmansHeatmaker: 107,
  FabricateTheCleanersCarbine: 108,
  FabricateBabyFacesBlaster: 109,
  FabricatePrettyBoysPocketPistol: 110,
  FabricateTheScorchShot: 111,
  FabricateTheNeonAnnihilator: 112,
  FabricateTheFlyingGuillotine: 113,
  FabricateTheHuoLongHeatmaker: 114,
  FabricateTheRedTapeRecorder: 115,
  PowerUpCanteen: 116,
  PileOfCurses: 117,
  FabricateTheRescueRanger: 118,
  FabricateTheLooseCannon: 119,
  FabricateTheVaccinator: 120,
  FabricateStickybombJumper: 121,
  FabricateRocketJumper: 122,
  FabricateTheAirStrike: 123,
  FabricateTheTideTurner: 124,
  FabricateTheBASEJumper: 125,
  FabricateTheClassic: 126,
  FabricateTheBackScatter: 127,
  FabricatePanicAttackShotgun: 128,
  FabricateTheIronBomber: 129,
  FabricateTheQuickiebombLauncher: 130,
  GiftapultGiftWrap: 131,
  StrangeCountTransferTool: 132,
}
